# Generated by Django 2.1.dev20180207233812 on 2018-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=255, null=True),
        ),
    ]
